ALTER TABLE users ADD COLUMN IF NOT EXISTS mining_started_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vip_subscription_end TIMESTAMP;
ALTER TABLE balances ADD COLUMN IF NOT EXISTS earned_sol DECIMAL(18,8) DEFAULT 0;
ALTER TABLE balances ADD COLUMN IF NOT EXISTS earned_eth DECIMAL(18,8) DEFAULT 0;
ALTER TABLE balances ADD COLUMN IF NOT EXISTS earned_usdt DECIMAL(18,8) DEFAULT 0;
ALTER TABLE balances ADD COLUMN IF NOT EXISTS earned_usdc DECIMAL(18,8) DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_deposit_tx_hash_unique
  ON deposit_requests(tx_hash);
