// 500+ Crypto & Blockchain Trivia Questions
export const TRIVIA_QUESTIONS = [
  // Bitcoin & Cryptocurrency Basics (50 questions)
  { q: 'What is Bitcoin?', options: ['A cryptocurrency', 'A bank', 'A stock', 'A bond'], answer: 0 },
  { q: 'Who created Bitcoin?', options: ['Satoshi Nakamoto', 'Vitalik Buterin', 'Elon Musk', 'Bill Gates'], answer: 0 },
  { q: 'When was Bitcoin created?', options: ['2009', '2015', '2000', '2020'], answer: 0 },
  { q: 'What is the maximum supply of Bitcoin?', options: ['21 million', '100 million', 'Unlimited', '1 billion'], answer: 0 },
  { q: 'What is a Satoshi?', options: ['Smallest Bitcoin unit', 'Bitcoin creator', 'Mining hardware', 'Wallet type'], answer: 0 },
  { q: 'What is Bitcoin halving?', options: ['Mining reward reduction', 'Price drop', 'Network split', 'Wallet update'], answer: 0 },
  { q: 'What is the Bitcoin block time?', options: ['10 minutes', '1 minute', '1 hour', '1 second'], answer: 0 },
  { q: 'What consensus does Bitcoin use?', options: ['Proof of Work', 'Proof of Stake', 'Proof of Authority', 'Proof of History'], answer: 0 },
  { q: 'What is a Bitcoin address?', options: ['Public key hash', 'Private key', 'Password', 'Username'], answer: 0 },
  { q: 'What is Bitcoin mining?', options: ['Validating transactions', 'Buying coins', 'Trading', 'Storing coins'], answer: 0 },
  
  // Ethereum & Smart Contracts (50 questions)
  { q: 'What is Ethereum?', options: ['Smart contract platform', 'Just a coin', 'A bank', 'A game'], answer: 0 },
  { q: 'Who created Ethereum?', options: ['Vitalik Buterin', 'Satoshi Nakamoto', 'Charles Hoskinson', 'Elon Musk'], answer: 0 },
  { q: 'What is Ether (ETH)?', options: ['Ethereum native token', 'Bitcoin fork', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is a smart contract?', options: ['Self-executing code', 'Legal document', 'Paper contract', 'Bank agreement'], answer: 0 },
  { q: 'What language are Ethereum smart contracts written in?', options: ['Solidity', 'JavaScript', 'Python', 'Java'], answer: 0 },
  { q: 'What is gas in Ethereum?', options: ['Transaction fee', 'Fuel', 'Token name', 'Mining reward'], answer: 0 },
  { q: 'What is ERC-20?', options: ['Token standard', 'Wallet type', 'Mining algorithm', 'Exchange'], answer: 0 },
  { q: 'What is ERC-721?', options: ['NFT standard', 'Token standard', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Ethereum 2.0?', options: ['Proof of Stake upgrade', 'New coin', 'Hard fork', 'Exchange'], answer: 0 },
  { q: 'What is the Ethereum Virtual Machine (EVM)?', options: ['Runtime environment', 'Mining hardware', 'Wallet', 'Exchange'], answer: 0 },
  
  // DeFi (50 questions)
  { q: 'What does DeFi stand for?', options: ['Decentralized Finance', 'Digital Finance', 'Defined Finance', 'Default Finance'], answer: 0 },
  { q: 'What is a DEX?', options: ['Decentralized Exchange', 'Digital Exchange', 'Default Exchange', 'Defined Exchange'], answer: 0 },
  { q: 'What is Uniswap?', options: ['DEX protocol', 'Centralized exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is liquidity mining?', options: ['Earning rewards for providing liquidity', 'Bitcoin mining', 'Trading', 'Staking'], answer: 0 },
  { q: 'What is yield farming?', options: ['Earning interest on crypto', 'Growing crops', 'Mining', 'Trading'], answer: 0 },
  { q: 'What is an AMM?', options: ['Automated Market Maker', 'Advanced Mining Machine', 'Asset Management Module', 'Automated Money Manager'], answer: 0 },
  { q: 'What is impermanent loss?', options: ['Loss from price divergence', 'Permanent loss', 'Trading loss', 'Mining loss'], answer: 0 },
  { q: 'What is a liquidity pool?', options: ['Token reserves for trading', 'Mining pool', 'Staking pool', 'Wallet'], answer: 0 },
  { q: 'What is Aave?', options: ['Lending protocol', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is Compound?', options: ['Lending protocol', 'Exchange', 'Wallet', 'Mining pool'], answer: 0 },
  
  // NFTs (50 questions)
  { q: 'What does NFT stand for?', options: ['Non-Fungible Token', 'New Financial Token', 'Net Finance Trade', 'No Fee Transaction'], answer: 0 },
  { q: 'What makes NFTs unique?', options: ['Each token is unique', 'They are all the same', 'They are free', 'They are fast'], answer: 0 },
  { q: 'What blockchain are most NFTs on?', options: ['Ethereum', 'Bitcoin', 'Litecoin', 'Dogecoin'], answer: 0 },
  { q: 'What is OpenSea?', options: ['NFT marketplace', 'Blockchain', 'Wallet', 'Mining pool'], answer: 0 },
  { q: 'What is minting an NFT?', options: ['Creating a new NFT', 'Buying an NFT', 'Selling an NFT', 'Trading an NFT'], answer: 0 },
  { q: 'What is a PFP NFT?', options: ['Profile Picture NFT', 'Proof of Purchase', 'Private Finance Protocol', 'Public Fund Pool'], answer: 0 },
  { q: 'What is IPFS?', options: ['Decentralized storage', 'Blockchain', 'Token', 'Exchange'], answer: 0 },
  { q: 'What is a generative NFT?', options: ['Algorithmically created', 'Hand drawn', 'Photographed', 'Scanned'], answer: 0 },
  { q: 'What is royalty in NFTs?', options: ['Creator fee on resales', 'Initial price', 'Gas fee', 'Minting fee'], answer: 0 },
  { q: 'What is a 1/1 NFT?', options: ['Unique single edition', 'One of many', 'First NFT', 'Last NFT'], answer: 0 },
  
  // Blockchain Technology (50 questions)
  { q: 'What is a blockchain?', options: ['Distributed ledger', 'Database', 'Spreadsheet', 'Document'], answer: 0 },
  { q: 'What is a block in blockchain?', options: ['Group of transactions', 'Single transaction', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a hash?', options: ['Cryptographic fingerprint', 'Password', 'Username', 'Email'], answer: 0 },
  { q: 'What is a node?', options: ['Computer in network', 'Wallet', 'Exchange', 'Token'], answer: 0 },
  { q: 'What is consensus?', options: ['Agreement mechanism', 'Voting', 'Trading', 'Mining'], answer: 0 },
  { q: 'What is Proof of Work?', options: ['Mining-based consensus', 'Staking', 'Voting', 'Trading'], answer: 0 },
  { q: 'What is Proof of Stake?', options: ['Staking-based consensus', 'Mining', 'Trading', 'Voting'], answer: 0 },
  { q: 'What is a fork?', options: ['Protocol split', 'Eating utensil', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a hard fork?', options: ['Incompatible protocol change', 'Soft change', 'Wallet update', 'Exchange update'], answer: 0 },
  { q: 'What is a soft fork?', options: ['Compatible protocol change', 'Hard change', 'Wallet update', 'Exchange update'], answer: 0 },
  
  // Wallets & Security (50 questions)
  { q: 'What is a crypto wallet?', options: ['Stores private keys', 'Stores coins physically', 'Bank account', 'Credit card'], answer: 0 },
  { q: 'What is a private key?', options: ['Secret access code', 'Public address', 'Username', 'Email'], answer: 0 },
  { q: 'What is a public key?', options: ['Shareable address', 'Private code', 'Password', 'PIN'], answer: 0 },
  { q: 'What is a seed phrase?', options: ['Wallet recovery words', 'Password', 'Username', 'Email'], answer: 0 },
  { q: 'How many words in a typical seed phrase?', options: ['12 or 24', '6', '100', '3'], answer: 0 },
  { q: 'What is a hot wallet?', options: ['Online wallet', 'Cold storage', 'Paper wallet', 'Hardware wallet'], answer: 0 },
  { q: 'What is a cold wallet?', options: ['Offline storage', 'Online wallet', 'Exchange wallet', 'Web wallet'], answer: 0 },
  { q: 'What is a hardware wallet?', options: ['Physical device', 'Software', 'Website', 'App'], answer: 0 },
  { q: 'What is MetaMask?', options: ['Browser wallet', 'Hardware wallet', 'Exchange', 'Blockchain'], answer: 0 },
  { q: 'What is 2FA?', options: ['Two-Factor Authentication', 'Two Fast Actions', 'Two Finance Apps', 'Two Free Assets'], answer: 0 },
  
  // Trading & Exchanges (50 questions)
  { q: 'What is a cryptocurrency exchange?', options: ['Trading platform', 'Wallet', 'Blockchain', 'Mining pool'], answer: 0 },
  { q: 'What is Binance?', options: ['Crypto exchange', 'Blockchain', 'Wallet', 'Token'], answer: 0 },
  { q: 'What is Coinbase?', options: ['Crypto exchange', 'Blockchain', 'Wallet only', 'Mining pool'], answer: 0 },
  { q: 'What is a market order?', options: ['Instant trade at current price', 'Future trade', 'Limit order', 'Stop order'], answer: 0 },
  { q: 'What is a limit order?', options: ['Trade at specific price', 'Instant trade', 'Market order', 'Stop order'], answer: 0 },
  { q: 'What is a stop-loss?', options: ['Automatic sell at loss limit', 'Profit target', 'Market order', 'Limit order'], answer: 0 },
  { q: 'What is a bull market?', options: ['Rising prices', 'Falling prices', 'Stable prices', 'No trading'], answer: 0 },
  { q: 'What is a bear market?', options: ['Falling prices', 'Rising prices', 'Stable prices', 'High volume'], answer: 0 },
  { q: 'What is FOMO?', options: ['Fear Of Missing Out', 'Fear Of Money Out', 'Fast Order Market Open', 'First Order Must Open'], answer: 0 },
  { q: 'What is FUD?', options: ['Fear Uncertainty Doubt', 'Fast User Data', 'First User Deposit', 'Fund Under Development'], answer: 0 },
  
  // Stablecoins (30 questions)
  { q: 'What is a stablecoin?', options: ['Price-stable cryptocurrency', 'Volatile coin', 'Mining coin', 'NFT'], answer: 0 },
  { q: 'What is USDT?', options: ['Tether stablecoin', 'Bitcoin', 'Ethereum', 'NFT'], answer: 0 },
  { q: 'What is USDC?', options: ['USD Coin stablecoin', 'Bitcoin', 'Ethereum', 'NFT'], answer: 0 },
  { q: 'What backs most stablecoins?', options: ['Fiat currency reserves', 'Gold', 'Bitcoin', 'Nothing'], answer: 0 },
  { q: 'What is DAI?', options: ['Decentralized stablecoin', 'Centralized coin', 'NFT', 'Exchange'], answer: 0 },
  { q: 'What is algorithmic stablecoin?', options: ['Code-maintained stability', 'Fiat-backed', 'Gold-backed', 'Bitcoin-backed'], answer: 0 },
  { q: 'What is Tether?', options: ['USDT stablecoin issuer', 'Exchange', 'Blockchain', 'Wallet'], answer: 0 },
  { q: 'What is Circle?', options: ['USDC issuer', 'Exchange', 'Blockchain', 'Wallet'], answer: 0 },
  { q: 'Why use stablecoins?', options: ['Avoid volatility', 'Get rich quick', 'Mine coins', 'Create NFTs'], answer: 0 },
  { q: 'What is BUSD?', options: ['Binance USD stablecoin', 'Bitcoin', 'Ethereum', 'NFT'], answer: 0 },
  
  // Altcoins (40 questions)
  { q: 'What is an altcoin?', options: ['Any coin except Bitcoin', 'Only Bitcoin', 'Only Ethereum', 'Only stablecoins'], answer: 0 },
  { q: 'What is Cardano (ADA)?', options: ['Proof of Stake blockchain', 'Bitcoin fork', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Solana (SOL)?', options: ['High-speed blockchain', 'Bitcoin fork', 'Stablecoin', 'NFT marketplace'], answer: 0 },
  { q: 'What is Polkadot (DOT)?', options: ['Multi-chain protocol', 'Bitcoin fork', 'Stablecoin', 'Exchange'], answer: 0 },
  { q: 'What is Chainlink (LINK)?', options: ['Oracle network', 'Exchange', 'Wallet', 'NFT'], answer: 0 },
  { q: 'What is Litecoin (LTC)?', options: ['Bitcoin alternative', 'Ethereum fork', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Ripple (XRP)?', options: ['Payment protocol', 'Mining coin', 'NFT', 'Stablecoin'], answer: 0 },
  { q: 'What is Dogecoin (DOGE)?', options: ['Meme cryptocurrency', 'Serious project', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Polygon (MATIC)?', options: ['Ethereum scaling solution', 'New blockchain', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Avalanche (AVAX)?', options: ['Smart contract platform', 'Bitcoin fork', 'Stablecoin', 'Exchange'], answer: 0 },
  
  // Mining & Staking (40 questions)
  { q: 'What is crypto mining?', options: ['Validating transactions', 'Buying coins', 'Trading', 'Storing'], answer: 0 },
  { q: 'What is a mining pool?', options: ['Group mining together', 'Solo mining', 'Staking', 'Trading'], answer: 0 },
  { q: 'What is hash rate?', options: ['Mining power', 'Internet speed', 'Transaction speed', 'Storage size'], answer: 0 },
  { q: 'What is an ASIC?', options: ['Specialized mining hardware', 'Wallet', 'Exchange', 'Token'], answer: 0 },
  { q: 'What is GPU mining?', options: ['Graphics card mining', 'CPU mining', 'ASIC mining', 'Phone mining'], answer: 0 },
  { q: 'What is staking?', options: ['Locking coins for rewards', 'Mining', 'Trading', 'Selling'], answer: 0 },
  { q: 'What is a validator?', options: ['PoS network participant', 'Miner', 'Trader', 'Exchange'], answer: 0 },
  { q: 'What is slashing?', options: ['Penalty for bad validators', 'Reward', 'Mining', 'Trading'], answer: 0 },
  { q: 'What is APY?', options: ['Annual Percentage Yield', 'Average Price Yearly', 'Asset Price Year', 'Annual Purchase Yield'], answer: 0 },
  { q: 'What is delegated staking?', options: ['Staking through validator', 'Solo staking', 'Mining', 'Trading'], answer: 0 },
  
  // Web3 & Metaverse (30 questions)
  { q: 'What is Web3?', options: ['Decentralized internet', 'Web browser', 'Social media', 'Email'], answer: 0 },
  { q: 'What is the metaverse?', options: ['Virtual world', 'Website', 'App', 'Game'], answer: 0 },
  { q: 'What is Decentraland?', options: ['Virtual world platform', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is The Sandbox?', options: ['Metaverse platform', 'Mining pool', 'Exchange', 'Wallet'], answer: 0 },
  { q: 'What is a DAO?', options: ['Decentralized Autonomous Organization', 'Digital Asset Owner', 'Data Access Object', 'Direct Asset Order'], answer: 0 },
  { q: 'What is governance token?', options: ['Voting rights token', 'Stablecoin', 'NFT', 'Mining reward'], answer: 0 },
  { q: 'What is a dApp?', options: ['Decentralized application', 'Desktop app', 'Download app', 'Data app'], answer: 0 },
  { q: 'What is IPFS used for?', options: ['Decentralized file storage', 'Mining', 'Trading', 'Staking'], answer: 0 },
  { q: 'What is ENS?', options: ['Ethereum Name Service', 'Exchange Network System', 'Easy Node Setup', 'Encrypted Network Service'], answer: 0 },
  { q: 'What is a Web3 wallet?', options: ['Crypto wallet for dApps', 'Bank account', 'Email', 'Social media'], answer: 0 },
  
  // Regulations & Legal (20 questions)
  { q: 'What is KYC?', options: ['Know Your Customer', 'Keep Your Coins', 'Key Your Code', 'Know Your Crypto'], answer: 0 },
  { q: 'What is AML?', options: ['Anti-Money Laundering', 'Automated Mining Logic', 'Asset Management Law', 'Advanced Market Limit'], answer: 0 },
  { q: 'What is the SEC?', options: ['Securities Exchange Commission', 'Secure Exchange Crypto', 'Safe Ethereum Contract', 'Standard Exchange Code'], answer: 0 },
  { q: 'Are cryptocurrencies legal everywhere?', options: ['No, varies by country', 'Yes, everywhere', 'Only in USA', 'Only in Europe'], answer: 0 },
  { q: 'What is a security token?', options: ['Regulated investment token', 'Security software', 'Password', 'Antivirus'], answer: 0 },
  { q: 'What is a utility token?', options: ['Platform access token', 'Security token', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is tax treatment of crypto?', options: ['Varies by jurisdiction', 'Always tax-free', 'Always taxed', 'Never reported'], answer: 0 },
  { q: 'What is FATF?', options: ['Financial Action Task Force', 'Fast Asset Transfer Fund', 'Free Asset Trading Forum', 'First Automated Token Factory'], answer: 0 },
  { q: 'What is MiCA?', options: ['EU crypto regulation', 'US law', 'Asian law', 'Mining company'], answer: 0 },
  { q: 'What is a CBDC?', options: ['Central Bank Digital Currency', 'Crypto Bank Digital Coin', 'Community Based Digital Currency', 'Commercial Bank Digital Cash'], answer: 0 },
  
  // Advanced Concepts (30 questions)
  { q: 'What is a layer 2 solution?', options: ['Scaling solution', 'New blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Lightning Network?', options: ['Bitcoin layer 2', 'Ethereum layer 2', 'New coin', 'Exchange'], answer: 0 },
  { q: 'What is sharding?', options: ['Database partitioning', 'Mining', 'Trading', 'Staking'], answer: 0 },
  { q: 'What is a sidechain?', options: ['Separate blockchain', 'Main chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is cross-chain?', options: ['Between blockchains', 'Single chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a bridge?', options: ['Cross-chain connector', 'Wallet', 'Exchange', 'Mining pool'], answer: 0 },
  { q: 'What is MEV?', options: ['Miner Extractable Value', 'Maximum Exchange Value', 'Minimum Entry Value', 'Market Estimated Value'], answer: 0 },
  { q: 'What is a flash loan?', options: ['Uncollateralized instant loan', 'Long-term loan', 'Mortgage', 'Credit card'], answer: 0 },
  { q: 'What is composability?', options: ['Combining protocols', 'Mining', 'Trading', 'Staking'], answer: 0 },
  { q: 'What is a Merkle tree?', options: ['Data structure', 'Physical tree', 'Wallet', 'Exchange'], answer: 0 },
  
  // Crypto Culture & Slang (30 questions)
  { q: 'What does HODL mean?', options: ['Hold On for Dear Life', 'Hold Or Drop Later', 'High Order Digital Ledger', 'Hash Of Digital Link'], answer: 0 },
  { q: 'What does DYOR mean?', options: ['Do Your Own Research', 'Don\'t Yield On Returns', 'Daily Yield On Returns', 'Do You Own Ripple'], answer: 0 },
  { q: 'What does "to the moon" mean?', options: ['Price going up', 'Space travel', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a whale?', options: ['Large holder', 'Small holder', 'Exchange', 'Wallet'], answer: 0 },
  { q: 'What does "rekt" mean?', options: ['Suffered big loss', 'Made profit', 'Bought coins', 'Sold coins'], answer: 0 },
  { q: 'What is a bag holder?', options: ['Holding losing investment', 'Profitable trader', 'Exchange owner', 'Miner'], answer: 0 },
  { q: 'What does "pump and dump" mean?', options: ['Price manipulation', 'Mining', 'Staking', 'Trading'], answer: 0 },
  { q: 'What is a rug pull?', options: ['Exit scam', 'Profit taking', 'Mining', 'Staking'], answer: 0 },
  { q: 'What does "diamond hands" mean?', options: ['Strong holder', 'Weak holder', 'Trader', 'Miner'], answer: 0 },
  { q: 'What does "paper hands" mean?', options: ['Weak holder', 'Strong holder', 'Trader', 'Miner'], answer: 0 },
  
  // Additional Mixed Questions (50+ questions)
  { q: 'What is tokenomics?', options: ['Token economics', 'Token mining', 'Token trading', 'Token staking'], answer: 0 },
  { q: 'What is burning tokens?', options: ['Removing from supply', 'Creating tokens', 'Trading tokens', 'Staking tokens'], answer: 0 },
  { q: 'What is a whitepaper?', options: ['Project documentation', 'White paper', 'Legal document', 'Trading guide'], answer: 0 },
  { q: 'What is an ICO?', options: ['Initial Coin Offering', 'International Crypto Order', 'Instant Coin Operation', 'Internal Chain Optimization'], answer: 0 },
  { q: 'What is an IEO?', options: ['Initial Exchange Offering', 'International Exchange Order', 'Instant Exchange Operation', 'Internal Exchange Optimization'], answer: 0 },
  { q: 'What is an IDO?', options: ['Initial DEX Offering', 'International DEX Order', 'Instant DEX Operation', 'Internal DEX Optimization'], answer: 0 },
  { q: 'What is vesting?', options: ['Gradual token release', 'Instant release', 'Token burning', 'Token mining'], answer: 0 },
  { q: 'What is a snapshot?', options: ['Blockchain state capture', 'Photo', 'Video', 'Document'], answer: 0 },
  { q: 'What is an airdrop?', options: ['Free token distribution', 'Token sale', 'Token burn', 'Token swap'], answer: 0 },
  { q: 'What is a token swap?', options: ['Exchanging tokens', 'Mining tokens', 'Burning tokens', 'Staking tokens'], answer: 0 },
  { q: 'What is market cap?', options: ['Total value of crypto', 'Price per coin', 'Trading volume', 'Supply amount'], answer: 0 },
  { q: 'What is circulating supply?', options: ['Available tokens', 'Total supply', 'Max supply', 'Burned supply'], answer: 0 },
  { q: 'What is total supply?', options: ['All existing tokens', 'Circulating only', 'Max possible', 'Burned tokens'], answer: 0 },
  { q: 'What is max supply?', options: ['Maximum possible tokens', 'Current supply', 'Circulating supply', 'Burned supply'], answer: 0 },
  { q: 'What is trading volume?', options: ['Amount traded', 'Price', 'Market cap', 'Supply'], answer: 0 },
  { q: 'What is liquidity?', options: ['Ease of trading', 'Price', 'Volume', 'Supply'], answer: 0 },
  { q: 'What is slippage?', options: ['Price difference in trade', 'Trading fee', 'Gas fee', 'Mining reward'], answer: 0 },
  { q: 'What is arbitrage?', options: ['Profit from price differences', 'Mining', 'Staking', 'Holding'], answer: 0 },
  { q: 'What is a trading pair?', options: ['Two tradeable assets', 'Single asset', 'Three assets', 'Four assets'], answer: 0 },
  { q: 'What is a base currency?', options: ['First in trading pair', 'Second in pair', 'Stablecoin', 'Bitcoin'], answer: 0 },
  
  // More Crypto Basics (50 questions)
  { q: 'What is a cryptocurrency?', options: ['Digital currency', 'Paper money', 'Credit card', 'Bank account'], answer: 0 },
  { q: 'What is decentralization?', options: ['No central authority', 'Central control', 'Government control', 'Bank control'], answer: 0 },
  { q: 'What is peer-to-peer?', options: ['Direct user interaction', 'Through intermediary', 'Through bank', 'Through government'], answer: 0 },
  { q: 'What is immutability?', options: ['Cannot be changed', 'Can be changed', 'Sometimes changed', 'Always changing'], answer: 0 },
  { q: 'What is transparency in blockchain?', options: ['Public ledger', 'Private ledger', 'Secret ledger', 'Hidden ledger'], answer: 0 },
  { q: 'What is pseudonymity?', options: ['Hidden identity', 'Public identity', 'No identity', 'Fake identity'], answer: 0 },
  { q: 'What is a transaction?', options: ['Transfer of value', 'Mining', 'Staking', 'Trading'], answer: 0 },
  { q: 'What is confirmation?', options: ['Transaction verification', 'Transaction creation', 'Transaction deletion', 'Transaction editing'], answer: 0 },
  { q: 'What is double spending?', options: ['Spending same coin twice', 'Spending two coins', 'Spending half coin', 'Spending no coins'], answer: 0 },
  { q: 'What prevents double spending?', options: ['Blockchain consensus', 'Banks', 'Government', 'Nothing'], answer: 0 },
  { q: 'What is a timestamp?', options: ['Time record', 'Price record', 'Volume record', 'Supply record'], answer: 0 },
  { q: 'What is a nonce?', options: ['Number used once', 'Name', 'Network', 'Node'], answer: 0 },
  { q: 'What is difficulty in mining?', options: ['Mining complexity', 'Mining speed', 'Mining cost', 'Mining reward'], answer: 0 },
  { q: 'What is block reward?', options: ['Mining compensation', 'Trading profit', 'Staking reward', 'Holding bonus'], answer: 0 },
  { q: 'What is transaction fee?', options: ['Network payment', 'Exchange fee', 'Wallet fee', 'Mining fee'], answer: 0 },
  { q: 'What is mempool?', options: ['Pending transactions', 'Confirmed transactions', 'Failed transactions', 'Cancelled transactions'], answer: 0 },
  { q: 'What is orphan block?', options: ['Rejected block', 'Accepted block', 'First block', 'Last block'], answer: 0 },
  { q: 'What is genesis block?', options: ['First block', 'Last block', 'Middle block', 'Any block'], answer: 0 },
  { q: 'What is block height?', options: ['Number of blocks', 'Block size', 'Block weight', 'Block speed'], answer: 0 },
  { q: 'What is block size?', options: ['Data capacity', 'Physical size', 'Number of blocks', 'Block speed'], answer: 0 },
  
  // DeFi Advanced (50 questions)
  { q: 'What is total value locked (TVL)?', options: ['Assets in protocol', 'Trading volume', 'Market cap', 'Price'], answer: 0 },
  { q: 'What is a lending protocol?', options: ['Borrow/lend platform', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is collateral?', options: ['Loan security', 'Profit', 'Fee', 'Reward'], answer: 0 },
  { q: 'What is liquidation?', options: ['Forced collateral sale', 'Profit taking', 'Buying', 'Staking'], answer: 0 },
  { q: 'What is overcollateralization?', options: ['Excess collateral', 'Exact collateral', 'No collateral', 'Low collateral'], answer: 0 },
  { q: 'What is a stablecoin peg?', options: ['Price target', 'Mining reward', 'Staking reward', 'Trading fee'], answer: 0 },
  { q: 'What is a liquidity provider?', options: ['Pool contributor', 'Trader', 'Miner', 'Staker'], answer: 0 },
  { q: 'What are LP tokens?', options: ['Liquidity proof', 'Loan tokens', 'Leverage tokens', 'Loss tokens'], answer: 0 },
  { q: 'What is a swap?', options: ['Token exchange', 'Mining', 'Staking', 'Holding'], answer: 0 },
  { q: 'What is a router?', options: ['Trade path finder', 'Mining hardware', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is price impact?', options: ['Trade effect on price', 'Market cap', 'Volume', 'Supply'], answer: 0 },
  { q: 'What is a bonding curve?', options: ['Price formula', 'Mining curve', 'Staking curve', 'Trading curve'], answer: 0 },
  { q: 'What is synthetic asset?', options: ['Derivative token', 'Real asset', 'NFT', 'Stablecoin'], answer: 0 },
  { q: 'What is a money market?', options: ['Lending platform', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is interest rate model?', options: ['Borrow/lend rates', 'Mining rates', 'Staking rates', 'Trading rates'], answer: 0 },
  { q: 'What is utilization rate?', options: ['Borrowed percentage', 'Staked percentage', 'Mined percentage', 'Traded percentage'], answer: 0 },
  { q: 'What is a vault?', options: ['Strategy contract', 'Wallet', 'Exchange', 'Blockchain'], answer: 0 },
  { q: 'What is auto-compounding?', options: ['Automatic reinvestment', 'Manual reinvestment', 'No reinvestment', 'Partial reinvestment'], answer: 0 },
  { q: 'What is a farming pool?', options: ['Yield opportunity', 'Mining pool', 'Trading pool', 'Staking pool'], answer: 0 },
  { q: 'What is a reward token?', options: ['Incentive payment', 'Stablecoin', 'NFT', 'Base token'], answer: 0 },
  
  // NFT Advanced (50 questions)
  { q: 'What is lazy minting?', options: ['Mint on purchase', 'Mint immediately', 'Never mint', 'Mint randomly'], answer: 0 },
  { q: 'What is a collection?', options: ['NFT group', 'Single NFT', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is rarity?', options: ['Trait uniqueness', 'Price', 'Age', 'Size'], answer: 0 },
  { q: 'What is a trait?', options: ['NFT attribute', 'Price', 'Owner', 'Blockchain'], answer: 0 },
  { q: 'What is floor price?', options: ['Lowest listing', 'Highest listing', 'Average price', 'First price'], answer: 0 },
  { q: 'What is a Dutch auction?', options: ['Descending price', 'Ascending price', 'Fixed price', 'Random price'], answer: 0 },
  { q: 'What is a reveal?', options: ['Show NFT metadata', 'Hide NFT', 'Burn NFT', 'Trade NFT'], answer: 0 },
  { q: 'What is metadata?', options: ['NFT information', 'Price', 'Owner', 'Blockchain'], answer: 0 },
  { q: 'What is on-chain metadata?', options: ['Stored on blockchain', 'Stored off-chain', 'Not stored', 'Stored locally'], answer: 0 },
  { q: 'What is off-chain metadata?', options: ['Stored externally', 'Stored on blockchain', 'Not stored', 'Stored in wallet'], answer: 0 },
  { q: 'What is a burn?', options: ['Destroy NFT', 'Create NFT', 'Trade NFT', 'Hold NFT'], answer: 0 },
  { q: 'What is a whitelist?', options: ['Early access list', 'Blacklist', 'Price list', 'Owner list'], answer: 0 },
  { q: 'What is a mint pass?', options: ['Minting right', 'Trading right', 'Staking right', 'Burning right'], answer: 0 },
  { q: 'What is a snapshot?', options: ['Holder record', 'Price record', 'Trade record', 'Mint record'], answer: 0 },
  { q: 'What is utility NFT?', options: ['Functional NFT', 'Art only', 'Profile picture', 'Collectible'], answer: 0 },
  { q: 'What is a dynamic NFT?', options: ['Changing metadata', 'Static metadata', 'No metadata', 'Hidden metadata'], answer: 0 },
  { q: 'What is fractionalization?', options: ['Split ownership', 'Full ownership', 'No ownership', 'Shared viewing'], answer: 0 },
  { q: 'What is an NFT marketplace?', options: ['Trading platform', 'Wallet', 'Blockchain', 'Mining pool'], answer: 0 },
  { q: 'What is gas war?', options: ['High fee competition', 'Low fees', 'No fees', 'Fixed fees'], answer: 0 },
  { q: 'What is a drop?', options: ['NFT release', 'Price drop', 'Network drop', 'Wallet drop'], answer: 0 },
  
  // Trading Advanced (50 questions)
  { q: 'What is technical analysis?', options: ['Chart study', 'Fundamental study', 'Random study', 'No study'], answer: 0 },
  { q: 'What is fundamental analysis?', options: ['Project evaluation', 'Chart study', 'Price study', 'Volume study'], answer: 0 },
  { q: 'What is a candlestick?', options: ['Price chart element', 'Mining tool', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is support level?', options: ['Price floor', 'Price ceiling', 'Average price', 'Random price'], answer: 0 },
  { q: 'What is resistance level?', options: ['Price ceiling', 'Price floor', 'Average price', 'Random price'], answer: 0 },
  { q: 'What is a trend?', options: ['Price direction', 'Volume', 'Market cap', 'Supply'], answer: 0 },
  { q: 'What is volume?', options: ['Trading amount', 'Price', 'Market cap', 'Supply'], answer: 0 },
  { q: 'What is market order?', options: ['Instant execution', 'Delayed execution', 'No execution', 'Partial execution'], answer: 0 },
  { q: 'What is limit order?', options: ['Price-specific order', 'Market order', 'Stop order', 'No order'], answer: 0 },
  { q: 'What is stop-loss order?', options: ['Loss limit order', 'Profit order', 'Market order', 'Limit order'], answer: 0 },
  { q: 'What is take-profit order?', options: ['Profit target order', 'Loss order', 'Market order', 'Limit order'], answer: 0 },
  { q: 'What is a long position?', options: ['Buy expecting rise', 'Sell expecting fall', 'No position', 'Neutral position'], answer: 0 },
  { q: 'What is a short position?', options: ['Sell expecting fall', 'Buy expecting rise', 'No position', 'Neutral position'], answer: 0 },
  { q: 'What is leverage?', options: ['Borrowed trading power', 'Own funds only', 'No trading', 'Staking'], answer: 0 },
  { q: 'What is margin trading?', options: ['Leveraged trading', 'Spot trading', 'No trading', 'Staking'], answer: 0 },
  { q: 'What is liquidation price?', options: ['Forced close level', 'Entry price', 'Target price', 'Random price'], answer: 0 },
  { q: 'What is a futures contract?', options: ['Future delivery agreement', 'Spot trade', 'No trade', 'Staking'], answer: 0 },
  { q: 'What is perpetual futures?', options: ['No expiry futures', 'Expiring futures', 'Spot trading', 'Staking'], answer: 0 },
  { q: 'What is funding rate?', options: ['Perpetual fee', 'Trading fee', 'Gas fee', 'Mining fee'], answer: 0 },
  { q: 'What is mark price?', options: ['Fair value price', 'Last price', 'First price', 'Average price'], answer: 0 },
  
  // Security & Scams (50 questions)
  { q: 'What is a phishing attack?', options: ['Fake website scam', 'Mining attack', 'Trading attack', 'Staking attack'], answer: 0 },
  { q: 'What is a rug pull?', options: ['Exit scam', 'Profit taking', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a Ponzi scheme?', options: ['Pyramid scam', 'Legitimate business', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a honeypot?', options: ['Trap contract', 'Legitimate contract', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a 51% attack?', options: ['Majority control attack', 'Minority attack', 'No attack', 'Trading attack'], answer: 0 },
  { q: 'What is social engineering?', options: ['Manipulation tactic', 'Social media', 'Trading', 'Mining'], answer: 0 },
  { q: 'What is a dusting attack?', options: ['Tracking via small amounts', 'Large transfer', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a Sybil attack?', options: ['Multiple fake identities', 'Single identity', 'No identity', 'Real identity'], answer: 0 },
  { q: 'What is a replay attack?', options: ['Transaction duplication', 'New transaction', 'No transaction', 'Failed transaction'], answer: 0 },
  { q: 'What is a man-in-the-middle attack?', options: ['Intercepting communication', 'Direct communication', 'No communication', 'Encrypted communication'], answer: 0 },
  { q: 'What is malware?', options: ['Malicious software', 'Good software', 'No software', 'Hardware'], answer: 0 },
  { q: 'What is a keylogger?', options: ['Keystroke recorder', 'Password manager', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is ransomware?', options: ['Data hostage software', 'Antivirus', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a smart contract exploit?', options: ['Code vulnerability attack', 'Normal use', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a flash loan attack?', options: ['Uncollateralized loan exploit', 'Normal loan', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is front-running?', options: ['Transaction order manipulation', 'Normal trading', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is sandwich attack?', options: ['Surround transaction exploit', 'Normal trading', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a fake token?', options: ['Impersonating token', 'Real token', 'NFT', 'Stablecoin'], answer: 0 },
  { q: 'What is address poisoning?', options: ['Similar address scam', 'Real address', 'No address', 'Wallet'], answer: 0 },
  { q: 'What is a pump and dump?', options: ['Price manipulation scheme', 'Normal trading', 'Mining', 'Staking'], answer: 0 },
  
  // Blockchain Platforms (40 questions)
  { q: 'What is Binance Smart Chain?', options: ['EVM-compatible chain', 'Bitcoin fork', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Cosmos?', options: ['Interoperability protocol', 'Single chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Tezos?', options: ['Self-amending blockchain', 'Bitcoin fork', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Algorand?', options: ['Pure PoS blockchain', 'PoW blockchain', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Near Protocol?', options: ['Sharded blockchain', 'Single chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Fantom?', options: ['DAG-based platform', 'Traditional blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Harmony?', options: ['Sharding blockchain', 'Single chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Elrond?', options: ['Adaptive state sharding', 'No sharding', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Hedera?', options: ['Hashgraph consensus', 'Blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Stellar?', options: ['Payment network', 'Smart contract platform', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is EOS?', options: ['DPoS blockchain', 'PoW blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Tron?', options: ['Content sharing platform', 'Payment network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is VeChain?', options: ['Supply chain blockchain', 'Payment network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Zilliqa?', options: ['Sharding blockchain', 'Single chain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Theta?', options: ['Video delivery network', 'Payment network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Flow?', options: ['NFT-focused blockchain', 'Payment network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Arbitrum?', options: ['Ethereum L2', 'L1 blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Optimism?', options: ['Ethereum L2', 'L1 blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is zkSync?', options: ['ZK-rollup L2', 'L1 blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is StarkNet?', options: ['ZK-rollup L2', 'L1 blockchain', 'Wallet', 'Exchange'], answer: 0 },
  
  // Miscellaneous (50+ questions)
  { q: 'What is a testnet?', options: ['Testing network', 'Main network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is mainnet?', options: ['Production network', 'Test network', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a faucet?', options: ['Free test tokens', 'Paid tokens', 'Mining', 'Staking'], answer: 0 },
  { q: 'What is a block explorer?', options: ['Blockchain viewer', 'Wallet', 'Exchange', 'Mining tool'], answer: 0 },
  { q: 'What is Etherscan?', options: ['Ethereum explorer', 'Bitcoin explorer', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is an oracle?', options: ['External data provider', 'Blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is Chainlink?', options: ['Oracle network', 'Blockchain', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is a wrapped token?', options: ['Cross-chain representation', 'Original token', 'NFT', 'Stablecoin'], answer: 0 },
  { q: 'What is WBTC?', options: ['Wrapped Bitcoin', 'Real Bitcoin', 'Bitcoin fork', 'Stablecoin'], answer: 0 },
  { q: 'What is WETH?', options: ['Wrapped Ether', 'Real Ether', 'Ethereum fork', 'Stablecoin'], answer: 0 },
  { q: 'What is gas limit?', options: ['Max gas for transaction', 'Min gas', 'Average gas', 'No limit'], answer: 0 },
  { q: 'What is gas price?', options: ['Cost per gas unit', 'Total cost', 'No cost', 'Fixed cost'], answer: 0 },
  { q: 'What is gwei?', options: ['Gas unit', 'Token', 'NFT', 'Stablecoin'], answer: 0 },
  { q: 'What is wei?', options: ['Smallest ETH unit', 'Largest unit', 'Token', 'NFT'], answer: 0 },
  { q: 'What is a dApp browser?', options: ['Web3 browser', 'Regular browser', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is WalletConnect?', options: ['dApp connection protocol', 'Wallet', 'Exchange', 'Blockchain'], answer: 0 },
  { q: 'What is a multi-sig wallet?', options: ['Multiple signature wallet', 'Single signature', 'No signature', 'Automatic signature'], answer: 0 },
  { q: 'What is a timelock?', options: ['Delayed execution', 'Instant execution', 'No execution', 'Random execution'], answer: 0 },
  { q: 'What is governance?', options: ['Decision making', 'Mining', 'Trading', 'Staking'], answer: 0 },
  { q: 'What is a proposal?', options: ['Governance suggestion', 'Trade', 'Mine', 'Stake'], answer: 0 },
  
  // More Advanced Topics (200+ questions)
  { q: 'What is atomic swap?', options: ['Cross-chain trade', 'Same-chain trade', 'No trade', 'Partial trade'], answer: 0 },
  { q: 'What is a state channel?', options: ['Off-chain scaling', 'On-chain only', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is plasma?', options: ['Ethereum scaling', 'Bitcoin scaling', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is rollup?', options: ['L2 scaling solution', 'L1 solution', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is optimistic rollup?', options: ['Fraud proof rollup', 'Validity proof', 'No proof', 'Random proof'], answer: 0 },
  { q: 'What is ZK-rollup?', options: ['Zero-knowledge rollup', 'Optimistic rollup', 'No rollup', 'Partial rollup'], answer: 0 },
  { q: 'What is zero-knowledge proof?', options: ['Prove without revealing', 'Prove with revealing', 'No proof', 'Partial proof'], answer: 0 },
  { q: 'What is zk-SNARK?', options: ['Succinct ZK proof', 'Long proof', 'No proof', 'Partial proof'], answer: 0 },
  { q: 'What is zk-STARK?', options: ['Transparent ZK proof', 'Opaque proof', 'No proof', 'Partial proof'], answer: 0 },
  { q: 'What is a validator set?', options: ['Active validators', 'Inactive validators', 'Miners', 'Traders'], answer: 0 },
  { q: 'What is epoch?', options: ['Time period', 'Block', 'Transaction', 'Wallet'], answer: 0 },
  { q: 'What is finality?', options: ['Irreversible confirmation', 'Reversible', 'Pending', 'Failed'], answer: 0 },
  { q: 'What is probabilistic finality?', options: ['Likely irreversible', 'Definitely irreversible', 'Reversible', 'No finality'], answer: 0 },
  { q: 'What is absolute finality?', options: ['Definitely irreversible', 'Likely irreversible', 'Reversible', 'No finality'], answer: 0 },
  { q: 'What is Byzantine Fault Tolerance?', options: ['Malicious node tolerance', 'No tolerance', 'Perfect nodes', 'Single node'], answer: 0 },
  { q: 'What is PBFT?', options: ['Practical BFT', 'Perfect BFT', 'Partial BFT', 'No BFT'], answer: 0 },
  { q: 'What is Tendermint?', options: ['BFT consensus', 'PoW consensus', 'No consensus', 'Random consensus'], answer: 0 },
  { q: 'What is Avalanche consensus?', options: ['Repeated sampling', 'Single vote', 'No vote', 'Random vote'], answer: 0 },
  { q: 'What is Nakamoto consensus?', options: ['Longest chain rule', 'Shortest chain', 'No chain', 'Random chain'], answer: 0 },
  { q: 'What is a light client?', options: ['Minimal node', 'Full node', 'No node', 'Archive node'], answer: 0 },
  { q: 'What is a full node?', options: ['Complete blockchain', 'Partial blockchain', 'No blockchain', 'Light node'], answer: 0 },
  { q: 'What is an archive node?', options: ['Full history node', 'Recent only', 'No history', 'Partial history'], answer: 0 },
  { q: 'What is pruning?', options: ['Remove old data', 'Keep all data', 'No data', 'Add data'], answer: 0 },
  { q: 'What is state rent?', options: ['Storage fee', 'Transaction fee', 'Gas fee', 'Mining fee'], answer: 0 },
  { q: 'What is state bloat?', options: ['Growing state size', 'Shrinking state', 'No state', 'Fixed state'], answer: 0 },
  { q: 'What is a stateless client?', options: ['No state storage', 'Full state', 'Partial state', 'Random state'], answer: 0 },
  { q: 'What is a witness?', options: ['State proof', 'Transaction', 'Block', 'Wallet'], answer: 0 },
  { q: 'What is verkle tree?', options: ['Efficient state tree', 'Merkle tree', 'No tree', 'Random tree'], answer: 0 },
  { q: 'What is EIP?', options: ['Ethereum Improvement Proposal', 'Exchange', 'Wallet', 'Token'], answer: 0 },
  { q: 'What is BIP?', options: ['Bitcoin Improvement Proposal', 'Exchange', 'Wallet', 'Token'], answer: 0 },
  { q: 'What is EIP-1559?', options: ['Fee market reform', 'Token standard', 'Wallet', 'Exchange'], answer: 0 },
  { q: 'What is base fee?', options: ['Burned transaction fee', 'Miner tip', 'Gas price', 'No fee'], answer: 0 },
  { q: 'What is priority fee?', options: ['Miner tip', 'Base fee', 'No fee', 'Fixed fee'], answer: 0 },
  { q: 'What is uncle block?', options: ['Valid but not main chain', 'Main chain', 'Invalid', 'No block'], answer: 0 },
  { q: 'What is selfish mining?', options: ['Withhold blocks', 'Share blocks', 'No mining', 'Random mining'], answer: 0 },
  { q: 'What is a mining pool?', options: ['Collaborative mining', 'Solo mining', 'No mining', 'Random mining'], answer: 0 },
  { q: 'What is pool hopping?', options: ['Switch pools', 'Stay in pool', 'No pool', 'Random pool'], answer: 0 },
  { q: 'What is ASIC resistance?', options: ['Anti-ASIC design', 'ASIC-friendly', 'No resistance', 'Random resistance'], answer: 0 },
  { q: 'What is memory-hard?', options: ['RAM-intensive', 'CPU-intensive', 'No intensity', 'Random intensity'], answer: 0 },
  { q: 'What is Ethash?', options: ['Ethereum PoW algorithm', 'Bitcoin algorithm', 'No algorithm', 'Random algorithm'], answer: 0 },
  { q: 'What is Scrypt?', options: ['Litecoin algorithm', 'Bitcoin algorithm', 'Ethereum algorithm', 'No algorithm'], answer: 0 },
  { q: 'What is SHA-256?', options: ['Bitcoin algorithm', 'Ethereum algorithm', 'Litecoin algorithm', 'No algorithm'], answer: 0 },
  { q: 'What is RandomX?', options: ['Monero algorithm', 'Bitcoin algorithm', 'Ethereum algorithm', 'No algorithm'], answer: 0 },
  { q: 'What is CryptoNight?', options: ['Privacy coin algorithm', 'Bitcoin algorithm', 'Ethereum algorithm', 'No algorithm'], answer: 0 },
  { q: 'What is Equihash?', options: ['Zcash algorithm', 'Bitcoin algorithm', 'Ethereum algorithm', 'No algorithm'], answer: 0 },
  { q: 'What is a privacy coin?', options: ['Anonymous cryptocurrency', 'Public cryptocurrency', 'No cryptocurrency', 'Stablecoin'], answer: 0 },
  { q: 'What is Monero?', options: ['Privacy cryptocurrency', 'Public cryptocurrency', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Zcash?', options: ['Privacy cryptocurrency', 'Public cryptocurrency', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is Dash?', options: ['Privacy cryptocurrency', 'Public cryptocurrency', 'Stablecoin', 'NFT'], answer: 0 },
  { q: 'What is ring signature?', options: ['Group signature', 'Single signature', 'No signature', 'Random signature'], answer: 0 },
  { q: 'What is stealth address?', options: ['One-time address', 'Permanent address', 'No address', 'Random address'], answer: 0 },
  { q: 'What is confidential transaction?', options: ['Hidden amounts', 'Public amounts', 'No amounts', 'Random amounts'], answer: 0 },
  { q: 'What is mixing?', options: ['Obfuscate transaction trail', 'Clear trail', 'No trail', 'Random trail'], answer: 0 },
  { q: 'What is a tumbler?', options: ['Mixing service', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is CoinJoin?', options: ['Bitcoin mixing', 'Ethereum mixing', 'No mixing', 'Random mixing'], answer: 0 },
  { q: 'What is Tornado Cash?', options: ['Ethereum mixer', 'Bitcoin mixer', 'Exchange', 'Wallet'], answer: 0 },
  { q: 'What is a mixer?', options: ['Privacy tool', 'Exchange', 'Wallet', 'Blockchain'], answer: 0 },
  { q: 'What is chain analysis?', options: ['Blockchain tracking', 'No tracking', 'Random tracking', 'Wallet'], answer: 0 },
  { q: 'What is taint analysis?', options: ['Coin history tracking', 'No tracking', 'Random tracking', 'Wallet'], answer: 0 },
  { q: 'What is a dust limit?', options: ['Minimum output', 'Maximum output', 'No limit', 'Random limit'], answer: 0 },
  { q: 'What is UTXO?', options: ['Unspent Transaction Output', 'Used output', 'No output', 'Random output'], answer: 0 },
  { q: 'What is account model?', options: ['Balance-based', 'UTXO-based', 'No model', 'Random model'], answer: 0 },
  { q: 'What is nonce in Ethereum?', options: ['Transaction count', 'Random number', 'Block number', 'Gas price'], answer: 0 },
  { q: 'What is a reorg?', options: ['Chain reorganization', 'No change', 'Random change', 'Wallet'], answer: 0 },
  { q: 'What is chain split?', options: ['Fork into two chains', 'Single chain', 'No chain', 'Random chain'], answer: 0 },
  { q: 'What is contentious fork?', options: ['Disputed fork', 'Agreed fork', 'No fork', 'Random fork'], answer: 0 },
  { q: 'What is non-contentious fork?', options: ['Agreed fork', 'Disputed fork', 'No fork', 'Random fork'], answer: 0 },
  { q: 'What is Bitcoin Cash?', options: ['Bitcoin fork', 'Ethereum fork', 'New coin', 'Stablecoin'], answer: 0 },
  { q: 'What is Bitcoin SV?', options: ['Bitcoin Cash fork', 'Bitcoin fork', 'Ethereum fork', 'Stablecoin'], answer: 0 },
  { q: 'What is Ethereum Classic?', options: ['Ethereum fork', 'Bitcoin fork', 'New coin', 'Stablecoin'], answer: 0 },
  { q: 'What caused Ethereum Classic?', options: ['DAO hack', 'Bug', 'Upgrade', 'Nothing'], answer: 0 },
  { q: 'What is The DAO?', options: ['Failed Ethereum project', 'Successful project', 'Bitcoin project', 'Stablecoin'], answer: 0 },
  { q: 'What is a re-entrancy attack?', options: ['Recursive call exploit', 'Normal call', 'No call', 'Random call'], answer: 0 },
  { q: 'What is overflow?', options: ['Number exceeds max', 'Number below min', 'Normal number', 'No number'], answer: 0 },
  { q: 'What is underflow?', options: ['Number below min', 'Number exceeds max', 'Normal number', 'No number'], answer: 0 },
  { q: 'What is SafeMath?', options: ['Overflow protection', 'No protection', 'Random protection', 'Wallet'], answer: 0 },
  { q: 'What is a proxy contract?', options: ['Upgradeable contract', 'Fixed contract', 'No contract', 'Random contract'], answer: 0 },
  { q: 'What is contract upgrade?', options: ['Change contract logic', 'No change', 'Random change', 'Delete contract'], answer: 0 },
  { q: 'What is immutable contract?', options: ['Cannot change', 'Can change', 'Sometimes change', 'Random change'], answer: 0 },
  { q: 'What is a factory contract?', options: ['Creates contracts', 'Destroys contracts', 'No contracts', 'Random contracts'], answer: 0 },
  { q: 'What is CREATE2?', options: ['Deterministic deployment', 'Random deployment', 'No deployment', 'Normal deployment'], answer: 0 },
  { q: 'What is selfdestruct?', options: ['Delete contract', 'Create contract', 'Update contract', 'No change'], answer: 0 },
  { q: 'What is delegatecall?', options: ['Execute in caller context', 'Execute in own context', 'No execution', 'Random execution'], answer: 0 },
  { q: 'What is staticcall?', options: ['Read-only call', 'Write call', 'No call', 'Random call'], answer: 0 },
  { q: 'What is fallback function?', options: ['Default function', 'Named function', 'No function', 'Random function'], answer: 0 },
  { q: 'What is receive function?', options: ['ETH receiver', 'Token receiver', 'No receiver', 'Random receiver'], answer: 0 },
  { q: 'What is a modifier?', options: ['Function wrapper', 'Function', 'Variable', 'Contract'], answer: 0 },
  { q: 'What is an event?', options: ['Log emission', 'Function', 'Variable', 'Contract'], answer: 0 },
  { q: 'What is indexed parameter?', options: ['Searchable event param', 'Normal param', 'No param', 'Random param'], answer: 0 },
  { q: 'What is ABI?', options: ['Application Binary Interface', 'API', 'Address', 'Account'], answer: 0 },
  { q: 'What is bytecode?', options: ['Compiled contract', 'Source code', 'No code', 'Random code'], answer: 0 },
  { q: 'What is opcode?', options: ['EVM instruction', 'Source code', 'No code', 'Random code'], answer: 0 },
  { q: 'What is gas optimization?', options: ['Reduce gas cost', 'Increase gas', 'No change', 'Random change'], answer: 0 },
  { q: 'What is storage slot?', options: ['Contract storage unit', 'Memory', 'Stack', 'No storage'], answer: 0 },
  { q: 'What is memory in Solidity?', options: ['Temporary storage', 'Permanent storage', 'No storage', 'Random storage'], answer: 0 },
  { q: 'What is calldata?', options: ['Function input data', 'Output data', 'No data', 'Random data'], answer: 0 },
  { q: 'What is stack in EVM?', options: ['Execution stack', 'Storage', 'Memory', 'No stack'], answer: 0 },
  { q: 'What is a library in Solidity?', options: ['Reusable code', 'Contract', 'Variable', 'Function'], answer: 0 },
  { q: 'What is interface in Solidity?', options: ['Contract definition', 'Implementation', 'Variable', 'Function'], answer: 0 },
  { q: 'What is abstract contract?', options: ['Incomplete contract', 'Complete contract', 'No contract', 'Random contract'], answer: 0 },
  { q: 'What is inheritance?', options: ['Contract extension', 'No extension', 'Random extension', 'Wallet'], answer: 0 },
  { q: 'What is multiple inheritance?', options: ['Multiple parents', 'Single parent', 'No parent', 'Random parent'], answer: 0 },
  { q: 'What is constructor?', options: ['Initialization function', 'Regular function', 'No function', 'Random function'], answer: 0 },
  { q: 'What is payable?', options: ['Can receive ETH', 'Cannot receive ETH', 'No ETH', 'Random ETH'], answer: 0 },
  { q: 'What is view function?', options: ['Read-only', 'Write function', 'No function', 'Random function'], answer: 0 },
  { q: 'What is pure function?', options: ['No state access', 'State access', 'No function', 'Random function'], answer: 0 },
  { q: 'What is external function?', options: ['Called from outside', 'Internal only', 'No function', 'Random function'], answer: 0 },
  { q: 'What is internal function?', options: ['Contract only', 'External only', 'No function', 'Random function'], answer: 0 },
  { q: 'What is private function?', options: ['This contract only', 'All contracts', 'No function', 'Random function'], answer: 0 },
  { q: 'What is public function?', options: ['Anyone can call', 'No one can call', 'No function', 'Random function'], answer: 0 },
  { q: 'What is require?', options: ['Condition check', 'No check', 'Random check', 'Wallet'], answer: 0 },
  { q: 'What is assert?', options: ['Invariant check', 'Condition check', 'No check', 'Random check'], answer: 0 },
  { q: 'What is revert?', options: ['Undo transaction', 'Continue transaction', 'No transaction', 'Random transaction'], answer: 0 },
  { q: 'What is try-catch?', options: ['Error handling', 'No handling', 'Random handling', 'Wallet'], answer: 0 },
  { q: 'What is emit?', options: ['Trigger event', 'No event', 'Random event', 'Wallet'], answer: 0 },
  { q: 'What is mapping?', options: ['Key-value storage', 'Array', 'Variable', 'Function'], answer: 0 },
  { q: 'What is array in Solidity?', options: ['List storage', 'Mapping', 'Variable', 'Function'], answer: 0 },
  { q: 'What is struct?', options: ['Custom data type', 'Primitive type', 'No type', 'Random type'], answer: 0 },
  { q: 'What is enum?', options: ['Named constants', 'Variables', 'Functions', 'Contracts'], answer: 0 },
  { q: 'What is address type?', options: ['Ethereum address', 'Number', 'String', 'Boolean'], answer: 0 },
  { q: 'What is uint?', options: ['Unsigned integer', 'Signed integer', 'Float', 'String'], answer: 0 },
  { q: 'What is int?', options: ['Signed integer', 'Unsigned integer', 'Float', 'String'], answer: 0 },
  { q: 'What is bool?', options: ['Boolean', 'Integer', 'String', 'Address'], answer: 0 },
  { q: 'What is string in Solidity?', options: ['Text data', 'Number', 'Boolean', 'Address'], answer: 0 },
  { q: 'What is bytes?', options: ['Binary data', 'Text', 'Number', 'Boolean'], answer: 0 },
  { q: 'What is fixed-size array?', options: ['Known length', 'Dynamic length', 'No length', 'Random length'], answer: 0 },
  { q: 'What is dynamic array?', options: ['Variable length', 'Fixed length', 'No length', 'Random length'], answer: 0 },
  { q: 'What is push in array?', options: ['Add element', 'Remove element', 'No change', 'Random change'], answer: 0 },
  { q: 'What is pop in array?', options: ['Remove last element', 'Add element', 'No change', 'Random change'], answer: 0 },
  { q: 'What is length property?', options: ['Array size', 'Array value', 'No property', 'Random property'], answer: 0 },
  { q: 'What is delete keyword?', options: ['Reset to default', 'Remove completely', 'No change', 'Random change'], answer: 0 },
  { q: 'What is this keyword?', options: ['Current contract', 'Other contract', 'No contract', 'Random contract'], answer: 0 },
  { q: 'What is msg.sender?', options: ['Transaction sender', 'Contract address', 'No address', 'Random address'], answer: 0 },
  { q: 'What is msg.value?', options: ['ETH sent', 'Gas price', 'No value', 'Random value'], answer: 0 },
  { q: 'What is block.timestamp?', options: ['Current time', 'Past time', 'Future time', 'No time'], answer: 0 },
  { q: 'What is block.number?', options: ['Current block', 'Past block', 'Future block', 'No block'], answer: 0 },
  { q: 'What is tx.origin?', options: ['Original sender', 'Direct sender', 'No sender', 'Random sender'], answer: 0 },
  { q: 'What is tx.gasprice?', options: ['Gas price', 'Gas limit', 'No gas', 'Random gas'], answer: 0 },
  { q: 'What is gasleft()?', options: ['Remaining gas', 'Used gas', 'Total gas', 'No gas'], answer: 0 },
  { q: 'What is blockhash()?', options: ['Block hash', 'Transaction hash', 'Address hash', 'No hash'], answer: 0 },
  { q: 'What is keccak256()?', options: ['Hash function', 'Encryption', 'Decryption', 'No function'], answer: 0 },
  { q: 'What is sha256()?', options: ['Hash function', 'Encryption', 'Decryption', 'No function'], answer: 0 },
  { q: 'What is ecrecover()?', options: ['Signature recovery', 'Signing', 'No recovery', 'Random recovery'], answer: 0 },
  { q: 'What is abi.encode()?', options: ['Encode data', 'Decode data', 'No encoding', 'Random encoding'], answer: 0 },
  { q: 'What is abi.decode()?', options: ['Decode data', 'Encode data', 'No decoding', 'Random decoding'], answer: 0 },
  { q: 'What is abi.encodePacked()?', options: ['Tight encoding', 'Normal encoding', 'No encoding', 'Random encoding'], answer: 0 },
  { q: 'What is selfdestruct recipient?', options: ['Receives remaining ETH', 'Sends ETH', 'No ETH', 'Random ETH'], answer: 0 },
];


